### ISSUE TITLE
Can't resolve 'fs'

### ISSUE THREAD

**Issue by Et3rnal** [gligoran/cordova-set-version#239]
I have installed it within my cordova/angular project but I'm getting

```
[ng] ERROR in ./node_modules/cordova-set-version/dist/index.js
[ng] Module not found: Error: Can't resolve 'fs' in 'C:\App\node_modules\cordova-set-version\dist'
```
when I add `const cordovaSetVersion = require('cordova-set-version');`

**Comment by gligoran** [comment]
Sorry for the late reply.

Are you running this code on the client side? If so, this is not really meant to be used that way.
The primary usage of this package is for development or CI via CLI.

If your using it in a script that runs this way, could you provide an example code that replicates this error?

**Comment by gligoran** [comment]
@Et3rnal has my comment fixed your problem? Can I close this issue?

**Comment by Et3rnal** [comment]
@gligoran Sorry I end up using something else. I want it something to execute before I do new builds.
