### ISSUE TITLE
Unable to npm install

### ISSUE THREAD

**Issue by john-doherty** [gligoran/cordova-set-version#54]
The install fails with node v9.1.0 with `npm ERR! Cannot read property '0' of undefined`

**Comment by gligoran** [comment]
Hey @john-doherty.

I tried it on macOs on 9.1.0 (installed via nvm) and it worked without a problem.

Can you specify your OS and also npm version?

**Comment by john-doherty** [comment]
Hi @gligoran, thanks for getting back to me. Turned out it was an issue with my environment and not `cordova-set-version` :)
