### ISSUE TITLE
TypeError: cordovaSetVersion is not a function

### ISSUE THREAD

**Issue by john-doherty** [gligoran/cordova-set-version#56]
Using your example in the readme, I get **TypeError: cordovaSetVersion is not a function**.

This is because your module exposes its method using: 

```js
exports.default = cordovaSetVersion;
```

Whereas it should be:

```js
module.exports = cordovaSetVersion;
```

`cordovaSetVersion.default();` works fine.

**Comment by gligoran** [comment]
Thanks for the report. It turns out it's how babel transpiles ES6 modules. I've changed the build process, so the package should now be usable as stated in the README.

**Comment by john-doherty** [comment]
Great, thanks @gligoran
